# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_manage_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=190, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=190, verbose_name='last_name')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default='', upload_to=user_manage_app.models.make_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
